# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: windows-2019

stages:
  - stage: Staging
    dependsOn: []
    jobs:
      - job:
        displayName: build-staging
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: "16.x"
          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: custom
              verbose: false
              customCommand: "ci"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: staging-build"
            inputs:
              ArtifactName: staging-build

  - stage: PROD
    dependsOn: []
    jobs:
      - job:
        displayName: build-prod
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: "16.x"
          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: custom
              verbose: false
              customCommand: "ci"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: ./
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: prod-build"
            inputs:
              ArtifactName: prod-build
