name: Build and Deploy app artifacts - QA / Staging / PROD
run-name: Build / Deploy ${{github.run_id}}.${{github.run_attempt}} - Create web artifacts

on:
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

env:
  HTTPS: ${{secrets.HTTPS}}
  VITE_SSO_OAUTH_CLIENT_ID: ${{secrets.VITE_SSO_OAUTH_CLIENT_ID}}
  VITE_SSO_OAUTH_SCOPE: ${{secrets.VITE_SSO_OAUTH_SCOPE}}
  SASS_PATH: ${{secrets.SASS_PATH}}

jobs:
  test-trigger:
    name: Trigger Testing
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    steps:
      - uses: actions/checkout@v3

      - name: Test
        if: env.HTTPS
        run: echo Injected environment variables

  qa:
    name: Build QA
    environment: qa
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine docker container image not avail on self-hosted runner
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: qa-build
          path: .

  staging:
    name: Build Staging
    environment: staging
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: .

  prod:
    name: Build PROD
    environment: prod
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: prod-build
          path: .

  deploy-qa:
    name: Deploy QA
    needs: [qa, staging, prod]
    environment: qa-release
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: qa-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls ./artifacts

      # - name: Zip the app contents
      #   uses: vimtor/action-zip@v1.2
      #   with:
      #     files: ./artifacts
      #     dest: app.zip

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Set SAS token expiration
        run: echo "expiry=`date -u -d "10" '+%Y-%m-%dT%H:%MZ'`" >> $GITHUB_ENV

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az extension add --name webapp

            az storage blob upload -f ./artifacts --account-name vitefsstorageqa -c app -n vitefsstorageqa
            ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{ env.expiry }}  --account-name vitefsstorageqa -c app -n vitefsstorageqa | xargs)
            az webapp deploy --name vite-fs-boilerplate-qa-app --resource-group vite-fs-rg-qa --type zip --src-url  $ZIP_URL --async false

  deploy-staging:
    name: Deploy Staging
    needs: [deploy-qa]
    environment: staging-release
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: staging-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls ./artifacts

  deploy-prod:
    name: Deploy PROD
    needs: [deploy-staging]
    environment: prod-release
    if: vars.PROD_ENABLED
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: prod-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls ./artifacts

