name: Deploy app artifacts - QA / Staging / PROD
run-name: Deploy All Builds ${{inputs.build-id}}-${{github.run_attempt}} - Deploy SPA artifacts to Azure

on:
  workflow_dispatch:
    inputs:
      build-id:
        description: "The id from the build"
        required: true

jobs:
  deploy-qa:
    name: Deploy QA
    needs: []
    environment: qa-release
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: qa-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts
        working-directory: ./artifacts

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ vars.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-staging:
    name: Deploy Staging
    needs: [deploy-qa]
    environment: staging-release
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: staging-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

  deploy-prod:
    name: Deploy PROD
    needs: [deploy-staging]
    environment: prod-release
    runs-on: [X64, macOS, self-hosted]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: prod-build
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

