name: Build backend architecture - QA / Staging
run-name: QA/Staging Infrastructure ${{inputs.run-id}}-tf.${{github.run_attempt}} - Create and/or update backend architecture

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: "The id from the build"
        required: true

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_VAR_AUTHOR: "${{ vars.AUTHOR }}"
  TF_VAR_AUTHOR_EMAIL: "${{ secrets.AUTHOR_EMAIL }}"
  TF_VAR_AUTHOR_GITHUB: "${{ vars.AUTHOR_GITHUB }}"
  TF_VAR_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
  TF_VAR_ALLOWED_IPS: "${{ secrets.ALLOWED_IPS }}"
  CONFIG_DIRECTORY: "./server/infra"

jobs:
  update-architecture-qa:
    name: Update Architecture - QA
    runs-on: [ubuntu-latest] # need to add self-hosted runner after docker install
    environment: qa
    env:
      TF_VAR_ENV: ${{vars.ENV}}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

  update-architecture-staging:
    name: Update Architecture - Staging
    needs: [update-architecture-qa]
    runs-on: [ubuntu-latest] # need to add self-hosted runner after docker install
    environment: staging
    env:
      TF_VAR_ENV: ${{ vars.ENV }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
