name: Build app artifacts thru Github pipelines
run-name: Build ${{github.run_number}}.${{github.run_attempt}} - Create SPA artifacts thru Github pipelines

on:
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

env:
  HTTPS: ${{secrets.HTTPS}}
  VITE_SSO_OAUTH_CLIENT_ID: ${{secrets.VITE_SSO_OAUTH_CLIENT_ID}}
  VITE_SSO_OAUTH_SCOPE: ${{secrets.VITE_SSO_OAUTH_SCOPE}}
  SASS_PATH: ${{secrets.SASS_PATH}}

jobs:
  test-trigger:
    name: Trigger Testing
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    steps:
      - uses: actions/checkout@v3

      - name: Test
        if: env.HTTPS
        run: echo Injected environment variables

  qa:
    name: Build QA
    environment: qa
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine docker container image not avail on self-hosted runner
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: qa-build
          path: .

  staging:
    name: Build Staging
    environment: staging
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: .

  prod:
    name: Build PROD
    environment: prod
    runs-on: [X64, macOS, self-hosted] # need to add self-hosted runner after docker install
    # container:
    #   image: node:20.15-alpine
    env:
      VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
      VITE_ENV: ${{secrets.VITE_ENV}}
      VITE_SSO_URL: ${{secrets.VITE_SSO_URL}}
      VITE_SSO_REDIRECT_URL: ${{secrets.VITE_SSO_REDIRECT_URL}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject env vars
        if: env.VITE_ENV
        run: echo Injected environment variables

      - name: Build client
        run: |
          cd client

      - name: npm install
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: prod-build
          path: .

